"""remodified datetime to current_timestamp, due to issue with asyncpg

Revision ID: 0ba0a61a47e6
Revises: 85713d3155eb
Create Date: 2025-03-09 00:08:28.777011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0ba0a61a47e6'
down_revision: Union[str, None] = '85713d3155eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
