"""Updated integrity constraints

Revision ID: 15496b3bbf81
Revises: ebe4bea711cc
Create Date: 2025-04-19 23:26:17.854718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15496b3bbf81'
down_revision: Union[str, None] = 'ebe4bea711cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genre_name', table_name='genre')
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.drop_index('ix_publisher_name', table_name='publisher')
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.create_index('ix_publisher_name', 'publisher', ['name'], unique=False)
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.create_index('ix_genre_name', 'genre', ['name'], unique=False)
    # ### end Alembic commands ###
