"""Fixed some foreign key issues

Revision ID: ebe4bea711cc
Revises: 2d8b4a45523e
Create Date: 2025-04-12 21:46:08.257037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe4bea711cc'
down_revision: Union[str, None] = '2d8b4a45523e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'book', 'publisher', ['publisher_id'], ['id'])
    op.create_unique_constraint(None, 'library', ['book_id'])
    op.create_unique_constraint(None, 'user_fine', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_fine', type_='unique')
    op.drop_constraint(None, 'library', type_='unique')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'publisher_id')
    op.drop_column('book', 'author_id')
    op.drop_column('book', 'genre_id')
    # ### end Alembic commands ###
